### PR TITLE
Compatiblility for Leaflet 1.0

### PR DESCRIPTION
**Pull request by brunob**
To merge on Leaflet 1.0 release...

Working examples : 

- [x] bing.html
- [x] deferred.html
- [x] gpx.html
- [x] gpx-no-wpt.html
- [x] gpx-speed.html
- [x] kml.html
- [x] marker-canvas.html
- [x] marker-rotate.html
- [x] marker-text.html
- [x] osm.html
- [x] permalink.html
- [x] topojson.html
- [x] yandex.html / have to check traffic layer

### CODE REVIEW

**Comment by miguelcobain** [comment]
What exactly is blocking this?

**Comment by brunob** [comment]
@miguelcobain just waiting the stable release of Leaflet core...

**Comment by miguelcobain** [comment]
@brunob ok. thanks.

FWIW, current leaflet rc is very stable, and it has been for a while.
It would be great to have leaflet 1 support in a bower pre-release version.

Also, it would let some devs to test it earlier rather than later.

**Comment by brunob** [comment]
@miguelcobain leaflet_one branch is now resynced with master, you can test it :)

**Comment by mattgrande** [comment]
Hey, just wondering if there's a release plan for this? If there's anything you need an extra set of eyes on, etc?

**Comment by brunob** [comment]
@mattgrande i'm on it...

**Comment by mattgrande** [comment]
Thanks!

**Comment by brunob** [comment]
@mattgrande anyway see #250

**Comment by brunob** [comment]
@nmccready since we'll remove google script here, could you please point me what can i safely remove in this branch for karma, google specs & dev dependencies etc ?

**Comment by nmccready** [comment]
@brunob sure why is the script being removed again. Just wondering if I need to use a other library for the next version. As for getting rid of karma,  sure go for it. However,  I recommend leaving it and doing a lot more specs for it.

**Comment by brunob** [comment]
> why is the script being removed again

@nmccready see #250 

> Just wondering if I need to use a other library for the next version

yes

**Comment by nmccready** [comment]
Awesome thank you

**Pull request merged**
