### PR TITLE
V1.9.3

### PR DESCRIPTION
**Pull request by joggienl**
I've tried to undo the made breaking change.
To do so I have made a branch of the 1.9.1 tag, and put the specific code for #226 in it. The branch is called 1.9.3.

### CODE REVIEW

**Comment by nmccready** [comment]
This needs to be merged to a 1.9.X or 1.X branch and not to master.

**Comment by joggienl** [comment]
Agreed! Can someone add a branch to which I can do this PR to?

**Comment by nmccready** [comment]
@brunob ?

> Agreed! Can someone add a branch to which I can do this PR to?

**Comment by brunob** [comment]
Done, branch v1 is there, can you change the target of your PR ?

**Comment by brunob** [comment]
Merged to branch v1, are we clear now or do i need to do something else ?

**Comment by joggienl** [comment]
Well, almost... the branch made was based on v2.0.0.. I did my pr on a branch based on 1.9.1

New PR for v1 is underway!

**Comment by joggienl** [comment]
New PR done with #249.

**Pull request merged**
