### PR TITLE
KML Layer Position

### PR DESCRIPTION
**Pull request by jonatan2m**
Hi,
First of all, thank you for this plugin.:)
I added some adjust in KML.j and I would like you analysis it, please.
First
When I put a Polilyne on the map, for example, at the intersection of my KML layer, the element is over the element. 
Do you think the KML layer always stay below the other elements?

Second
The rotation didn't work properly, I fixed it.

### CODE REVIEW

**Comment by brunob** [comment]
@jonatan2m any news about this ?

**Comment by jonatan2m** [comment]
Hello @brunob!
I apologize for the delay in responding...
The first point is just that.
The second point is difficult to reproduce today. 
But if no one mentioned anything about it , let's forget it.
Thanks again!

**Comment by brunob** [comment]
> The first point is just that.

Not sure about changing this, cause this would impact all the websites that use this script, and you can use bringToBack() on KML layers in your maps.

I let this one open for a while in order to let other people tell us what they think about it.

**Comment by jonatan2m** [comment]
Ok.
I think this option did not work...
If I get error again, I'll put on jsfiddle, ok?

2015-03-21 7:17 GMT-03:00 b_b <notifications@github.com>:

> The first point is just that.
>
> Not sure about changing this, cause this would impact all the websites
> that use this script, and you can use bringToBack() on KML layers in your
> maps.
>
> I let this one open for a while in order to let other people tell us what
> they think about it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shramov/leaflet-plugins/pull/143#issuecomment-84300738>
> .
>



-- 
Att,
Jonatan Machado

   [image: http://] <http://twitter.com/jonatanmachado>   [image: fda]
<https://www.linkedin.com/pub/jonatan-machado/13/678/268/pt>

**Comment by brunob** [comment]
@jonatan2m do you think we can close this issue ? (and propose a new one with only the part that works for opinion)

**Comment by jonatan2m** [comment]
Yes, I think so.
If I have this problem again I put on fiddle.


-----Original Message-----

**Comment by brunob** [comment]
nice :)

**Pull request closed without merging**
