### PR TITLE
L.BingLayer: fix some edge usage cases

### PR DESCRIPTION
**Pull request by johnd0e**
This change is [Reviewable](https://reviewable.io/reviews/shramov/leaflet-plugins/290)

### CODE REVIEW

**Comment by brunob** [comment]
Ready to merge @johnd0e ?

**Comment by johnd0e** [comment]
I need an advise:
`applyMaxNativeZoom` is not core functionality.
May be better to refactor it out into separate addon (like in `L.Yandex`)?

**Comment by brunob** [comment]
I don't think it's necessary to put it in separate addon just because it's not a core functionality, but... if you think it will charge memory or make much more requests it would be clever to put it in a separate script.

**Comment by johnd0e** [comment]
> it will charge memory or make much more requests

Nothing like this.
But it is sort of custom functionality, based on undocumented features.
So that part is just not as stable as core.

**Comment by johnd0e** [comment]
@brunob 
Ready to merge

**Comment by brunob** [comment]
Merged and relased, thx !

**Pull request merged**
