### PR TITLE
fire load event on tilesloaded

### PR DESCRIPTION
**Pull request by packowitz**
fire a load event when google maps initially is done loading all tiles.

### CODE REVIEW

**Comment by brunob** [comment]
Thanks for the patch, seems good to merge, you just have to fix formatting by using tabs like the rest of the file.

**Comment by brunob** [comment]
@packowitz can you replace spaces by tabs in order to merge it please ?

**Comment by packowitz** [comment]
My second commit should have done exactly that.

**Comment by brunob** [comment]
it doesn't seem so, really :p

**Pull request merged**
