### PR TITLE
fix: yandex zoom animation

### PR DESCRIPTION
**Pull request by oranmor**
https://github.com/shramov/leaflet-plugins/issues/129

### CODE REVIEW

**Comment by johnd0e** [comment]
Unfortunately animation is delayed, and not synchronized with other leaflet objects.
Just add any marker to see it:
```
L.marker([67.6755, 33.936]).addTo(map);
```

**Comment by oranmor** [comment]
I see. I've added a zoomanim event, it's no longer delayed, but the sync isn't 100% accurate.

**Comment by johnd0e** [comment]
Normally we do not need to implement animation by ourselves, as it processed by Leaflet, via css transition.
Animating transition via ymaps API looks like workaround.
But we should try to find proper solution.

I do not know why transition is not applied to ymaps container.

At first I thought that it may be related to asynchronousness of ymaps API (all that `setZoom`, `setCenter`, `panTo` return promises).
But I haven't find places in code where this might impact.

So question is what's wrong with ymaps container? Why it is not processed by leaflet animation routines?
We have no such issue with similar google plugin.

**Comment by johnd0e** [comment]
> I've added a zoomanim event,

Now `_update` is called twice, and it leads to unpleasant artifacts.

**Comment by oranmor** [comment]
@johnd0e I can't reproduce this. Perhaps it called twice because you have two yandex layers on the map? There are two of them in yandex.html example (normal map and traffic map). Try to disable traffic.

**Comment by johnd0e** [comment]
> I can't reproduce this.

I mean `setCenter`.

1. zoomanim event -> `_zoomAnim` -> `setCenter`
2. moveend event -> `_update` -> `setCenter`

**Comment by brunob** [comment]
Should this one be closed in favor of #285 ?

**Comment by johnd0e** [comment]
No.
#285 contains only part not related to zoom animation.

**Comment by johnd0e** [comment]
@oranmor 
> So question is what's wrong with ymaps container? Why it is not processed by leaflet animation routines?
> We have no such issue with similar google plugin.

As I figured out, GoogleMutant is based on `L.GridLayer`, which has some routines like `_animateZoom`.
It may be possible to re-implement similar routines for Yandex.

**Comment by johnd0e** [comment]
@brunob 
Fix is included in #285 now.

**Comment by brunob** [comment]
So we can close this one ?

**Comment by johnd0e** [comment]
Sure, if @oranmor is happy with my fix

**Comment by brunob** [comment]
Closing in favor of #285

**Pull request closed without merging**
