### PR TITLE
Yandex.addon.LoadApi.js: reimplemented in more straight-forward way

### PR DESCRIPTION
**Pull request by johnd0e**
`loadApi` is static function now

### CODE REVIEW

**Comment by brunob** [comment]
Nice, feel free to ping when ready to merge :)

**Comment by gelinger777** [comment]
hi @shramov  is there any short manual how to implement yandex plugin for leaflet for angular mobile apps? I  am using Ionic as a base , and can't reallt figure out how to npm install it and use it inisde ionic environment.. All you demos seems are for web people. Maybe you could give a link or an example... I just need to 
import * from  'leaflet_plugins' or what?
I would appreciate if you  or anybody could help out with Yandex maps on ionic

**Comment by johnd0e** [comment]
@brunob I can't remember why it is draft)

**Comment by brunob** [comment]
Thx for the feedback, let's merge it :)

**Pull request merged**
