### PR TITLE
GPX.js: provide more data to addpoint event

### PR DESCRIPTION
**Pull request by voda**
I use this code for setting custom icons to waypoints. I had this code in an two years old version of this library, but have found no traces of it in the git repo. So not sure if I have written the code or found it somewhere..

### CODE REVIEW

**Comment by brunob** [comment]
Hi @voda could you provide a demo page that show the use of this one please ?

**Comment by voda** [comment]
Sorry for the delay, my page is not currently working, so for now here is the code, that i use:
```js
var track = new L.GPX(...);
track.on('addpoint', function(args) {
  // icons is an array of L.Icon.extend
  args.point.setIcon(new icons[args.attrs.sym]);
});
map.addLayer(track);
```

**Comment by voda** [comment]
Here is the page where I am using it: http://fatra.vodacek.eu/

**Comment by brunob** [comment]
@voda sorry for the delay, i'd like to merge it, but i have a doubt on `attrs` property name, maybe something like attributes or properties would be clearer ? Any thoughts about it ?

Another point, it would be great if you could also modify gpx.html example file to show simple usage of this.

**Comment by voda** [comment]
Hi, renamed attr to attributes and modified the example. I used an icon from http://leafletjs.com/examples/custom-icons.html, so hope thats ok.

**Comment by brunob** [comment]
Thx @voda merged an published in version 1.4.1 :)

**Pull request merged**
